### ISSUE TITLE
Order and LDP

### ISSUE THREAD

**Issue by azaroth42** [duraspace/pcdm#11]
Beyond the abstract model in #10, there are further decisions regarding the LDP projection.

The proposal is:
- Establish a direct container called /orders/ associated with a pcdm:Object
- Order objects would be created within it, rather than referenced from elsewhere
- The container would assert hasRelatedObject / orderedBy to the parent Object
- Other than the potential for an Order class, the child Object is just the same as all other Objects (and thus has sub-containers for membership, files, etc.)

Thus, the URL paths would follow the pattern:

/object1
/object1/members/
/object1/members/proxy1
/object1/members/proxy2
/object1/members/proxyn
/object1/orders/
/object1/orders/order1
/object1/orders/order1/members/
/object1/orders/order1/members/oproxy2
/object1/orders/order1/members/oproxy1
/object1/orders/order1/members/oproxyn

With the ordering relationships, assuming that the first two member objects have switched:

object1 iana:first proxy1
proxy1 iana:next proxy2
order1 iana:first oproxy2
oproxy2 iana:next oproxy1

(and all of the other containers are available, just not explicit in the list above)

**Comment by azaroth42** [comment]
I think this issue can be closed?

**Comment by escowles** [comment]
+1 to closing
