### ISSUE TITLE
Can http://pcdm.org/models#Object extend http://www.w3.org/2006/gen/ont#InformationResource

### ISSUE THREAD

**Issue by jcoyne** [duraspace/pcdm#13]
This would tie it in with www.w3.org/ns/auth/acl#accessTo which has a range of http://www.w3.org/2006/gen/ont#InformationResource

**Comment by acoburn** [comment]
My understanding is that `rdfs:range` is for use by inference engines, not for validation. That is, you can assert: `<agent> acl:accessTo <resource>`, where `<resource>` may not already have any existing connection to `InformationResource`. With RDF, you can make any assertion you want, regardless of the existing `rdf:type` of a subject/object.

In a word, I don't think this is necessary.

**Comment by awoods** [comment]
@acoburn, although technically speaking, there does seem to value in being internally consistent given the move towards WebAC as @jcoyne notes.

**Comment by azaroth42** [comment]
Actually both pcdm:Collection and pcdm:Object are NonInformationResources due to their inheritance from ore:Aggregation. They have might one or more InformationResources, which are serializations in different formats, such as json-ld and turtle.

I agree with @acoburn regarding range (and domain)... but InformationResource and NonInformationResource are (one imagines) disjoint classes.  I agree that WebACL pattern is valuable, but we should be clear about what our IRs and NIRs are first.

**Comment by jcoyne** [comment]
@azaroth42 Thanks for looking into that. I didn't even notice the inheritance from ore:Aggregation. It does seem a bit odd that an object is a NonInformationalResource as we are putting a bunch of metadata there.

**Comment by escowles** [comment]
@azaroth42 I don't follow you from ore:Aggregation to gen:NonInformationResource.  I'm looking at http://www.openarchives.org/ore/terms/Aggregation and ore:Aggregation is subclassOf dcmitype:Collection.  The current dcmitype:Collection (http://dublincore.org/2012/06/14/dctype.rdf) doesn't list any superclasses.  What am I missing?

**Comment by azaroth42** [comment]
Nothing other than the timeline ... when we were documenting ORE we didn't have the Non / Information Resource terminology or ontology, or at least were completely unaware of it if it did exist.  

However from the ORE data model, the NIR-ness is, I think, clear:

> A URI-A MUST be a protocol-based URI. However, an Aggregation is a conceptual construct, and thus it does not have a Representation.

From: http://www.openarchives.org/ore/1.0/datamodel#Aggregation

**Comment by escowles** [comment]
OK, it looks like I've been conflating Aggregation and ResourceMap.  And I'm not really sure how ResourceMap would fit in the LDP and/or Fedora contexts.  Are the different RDF serializations of the Aggregation different ResourceMaps?  Is it OK that they all have the same URI (assuming content negotiation)?
