### ISSUE TITLE
Remove the declared transitivity of `ldp:contains`

### ISSUE THREAD

**Issue by no-reply** [duraspace/pcdm#33]
`ldp:contains` is declared to be transitive for [Administrative Sets](https://github.com/duraspace/pcdm/wiki#subclass-of-ldpcontainer), but we also say that any PCDM resource may be contained by at most one other resource.  These two assertions preclude nested Administrative Sets, since any member of the sub-set will be contained transitively.

The LDP vocabulary seems to have nothing to say about either of these restrictions; though, as a practical matter, singular containment seems fair to assume.

**Comment by escowles** [comment]
Looks like there's still discussion about transitivity going on in #29, but I've removed the sentence from the wiki that said ldp:contains was transitive: https://github.com/duraspace/pcdm/wiki/Home/_compare/54db360122c38bd2ffe3ca92965d9f35783ae0b6
